In [1]:
import numpy as np

In [2]:
X = np.array([1,2,3])
y = np.array([2,3,5])

In [3]:
X

array([1, 2, 3])

In [4]:
y

array([2, 3, 5])

In [51]:
iteration = 10000
learning_rate = 0.01
m = 1
b = 1
n = len(X)


In [52]:
m * X + b

1*1+1, 1*2+1, 1*3+1

(2, 3, 4)

In [53]:
for i in range(iteration):
  #print("input :", X)
  y_pred = m * X + b
  #print("y  : ", y)
  #print("y_pred : ", y_pred)

  error =  y - y_pred
  #print("Error array : ", error)
  error_sum = abs(np.sum(error))
  #print("Error Sum : ", error_sum)
  SSE = abs(np.sum(error))**2
  #print("SSE : ", SSE)
  MSE = (abs(np.sum(error))**2)/n
  #print("MSE : ", MSE)

  m_gradient = (2/n) * -(np.dot(X, error))
  #print("m_gradient : ", m_gradient)

  b_gradient = (2/n) * -(np.sum(error))
  #print("b_gradient : ", b_gradient)

  m = m - (learning_rate * m_gradient)
  #print("m : ", m)

  b = b - (learning_rate * b_gradient)
  #print("b : ", b)







print("m : ", m)
print("b : ", b)









m :  1.499999999988477
b :  0.33333333335952775


In [54]:
X

array([1, 2, 3])

In [55]:
y

array([2, 3, 5])

In [56]:
from sklearn.linear_model import LinearRegression

In [57]:
model = LinearRegression()

In [58]:
y

array([2, 3, 5])

In [59]:
model.fit(X.reshape(-1, 1),y)

LinearRegression()

In [60]:
model.coef_

array([1.5])

In [61]:
model.intercept_

np.float64(0.3333333333333348)

In [62]:
y_pred = model.predict(X.reshape(-1, 1))

In [63]:
from sklearn.metrics import mean_squared_error, mean_absolute_error

In [64]:
mean_squared_error(y, y_pred)

0.05555555555555553

In [65]:
from sklearn.linear_model import SGDRegressor

In [103]:
model = SGDRegressor(max_iter=1000, penalty=None)

In [104]:
model.fit(X.reshape(-1, 1),y)

SGDRegressor(penalty=None)

In [105]:
model.coef_

array([1.34381486])

In [106]:
model.intercept_

array([0.57293285])